Add unit testing to the components
baobabsoluciones/mango-ui pull request #40
Opened 2024-08-05 08:38 UTC by HelenaCA

2024-08-05 09:32 UTC, ggsdc requested changes

2024-08-05 09:32 UTC, ggsdc commented on .github/workflows/ci.yml
> +      - master
Missing that should also be run on develop

2024-09-16 11:08 UTC, ggsdc commented
What is missing in this PR?

2024-09-18 13:41 UTC, HelenaCA commented
Everything is done

2024-09-18 15:57 UTC, ggsdc approved these changes

2024-09-18 17:37 UTC, merged